substitutions:
  name: muse-proto
  friendly_name: Raspiaudio Muse Proto
#States  
  P_starting: "0"
  P_waiting: "1"
  P_playing: "2"
  P_listening: "3"
  P_answering: "4"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.2.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi
  project:
    name: raspiaudio.protoVoice-assistant
    version: "2025.2.2"    
  on_boot:
    priority: -100.0
    then:
      - lambda: id(phase) = 0;
      - script.execute: update_led  
            

        
esp32:
  board: esp-wrover-kit  
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
       
micro_wake_word:
  id: mww
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
#   - model: hey_jarvis
#    - model: hey_mycroft
#    - model: alexa
#  vad:
  microphone: proto_mic
  on_wake_word_detected:        
    - voice_assistant.start:
        wake_word: !lambda return wake_word;       

ota:                 
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request
   
#update:
#  - platform: http_request
#    id: update_http_request
#    name: Firmware
#    source: https://raw.githubusercontent.com/RASPIAUDIO/esphomeLuxe/main/manifest_update.json 
    
        
http_request:  
    
api:

wifi:
#  ssid: SSSSS
#  password: PPPPP
  power_save_mode: none
  output_power: 15
  ap:
     ssid: "Raspiaudio-proto"
     password: "12345678"

captive_portal:
                
#improv_serial: 

logger:
   level: DEBUG

##########
# Hardware Configuration
   
#psram:
#  mode: octal
#  speed: 80MHz

#######
# Buses Configuration
#i2c:
#  sda: GPIO18
#  scl: GPIO23


#####################
# Internal Components
output:
  - platform: gpio
    id: dac_mute
    pin:
      number: GPIO21
      inverted: true
      mode:
        output: true
  - platform: gpio
    id: gain
    pin: 
      number: GPIO23
      inverted: true
      mode:
        output: true   
                

globals:
  - id: Vol
    type: float
    initial_value: '0.6'    
  - id: phase
    type: int
    initial_value: '0'    
  - id: mute  
    type: bool
    initial_value: 'false'        
        
sensor:

                   
binary_sensor:
 


light:
  - platform: esp32_rmt_led_strip
    name: None
    id: top_led
    pin: GPIO22
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
#    rmt_channel: 0
    default_transition_length: 0s
    gamma_correct: 2.8
    effects:
      - pulse:
          name: pulse
          transition_length: 250ms
          update_interval: 250ms
      - pulse:
          name: slow_pulse
          transition_length: 1s
          update_interval: 2s

    
i2s_audio:
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5
    i2s_mclk_pin: GPIO0

microphone:
  - platform: i2s_audio
    id: proto_mic
    sample_rate: 16000
    i2s_din_pin: GPIO35
    bits_per_sample: 16bit
    channel: right
    adc_type: external  
    
speaker:
  - platform: i2s_audio
    id: luxe_speaker
    i2s_dout_pin: GPIO26
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: stereo
    buffer_duration: 100ms     
    
media_player:
  - platform: speaker
    name: None
    id: luxe_media_player
#    volume_min: 0.5
#    volume_max: 0.8
    announcement_pipeline:
      speaker: luxe_speaker
      format: FLAC
      sample_rate: 48000
      num_channels: 2  
    files:
      - id: little_sound
        file: https://github.com/esphome/home-assistant-voice-pe/raw/dev/sounds/timer_finished.flac          
    on_announcement: 
      - micro_wake_word.stop:
      - if:
           condition:
                lambda: 'return(id(phase) != 2);'
           then:           
              - lambda: |-
                   if(id(phase) == 1)  id(phase) = 2;    
              - script.execute: mute_off         
              - script.execute: update_led    
                     
    on_idle:
      - wait_until:
         and:
          - not:
              media_player.is_announcing:
          - not:
              voice_assistant.is_running:    
      - if:
          condition:              
              lambda: 'return((id(phase) == 4) || (id(phase) == 2));'
          then:
            - lambda: |-
                 id(phase) = 1; 
      - micro_wake_word.start:                                                
      - script.execute: update_led     
      

voice_assistant:
  id: va
  microphone: proto_mic
  media_player: luxe_media_player
  use_wake_word: false
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  
  on_listening: 
     - logger.log: "listening 3 => phase"                    
     - micro_wake_word.stop:
     - lambda: |-
        id(phase) = 3;                            
     - script.execute: update_led

  on_stt_end:
     - media_player.play_media: !lambda return x;
     - light.turn_on:
        id: top_led
        blue: 60%
        red: 20%
        green: 20%
        effect: pulse
      

  on_tts_start:
     - logger.log: "answering  4 => phase"                   
     - lambda: |-
        id(phase) = 4;
     - script.execute: update_led
                     
  on_error:
    - logger.log: "ERROR!!!!!!!!!!!!!!!!"  
    - light.turn_on:
        id: top_led
        blue: 0%
        red: 100%
        green: 0%
        effect: pulse          
    - delay: 3s
    - lambda: id(phase) = 1;    
    - script.execute: update_led 
  

#########
# Scripts

script:   
  - id: update_led
    then:  
       - logger.log: "==>>>update_led" 
       - lambda: |-
             if(id(phase) == 0)id(start).execute();
             if(id(phase) == 1)id(waiting).execute();  
             if(id(phase) == 2)id(external_player).execute();                      
             if(id(phase) == 3)id(listening).execute();
             if(id(phase) == 4)id(answering).execute();
                         
  - id: start           
    then:
     - light.turn_on:
          id: top_led
          effect: slow_pulse
          red: 80%
          green: 0%
          blue: 80%             
     - delay: 5sec
#     - lambda: id(my_es8388).setup();
     - voice_assistant.start:
     - media_player.volume_set: 90%
     - media_player.speaker.play_on_device_media_file:
          media_file: little_sound
          announcement: true     
     - output.turn_off: dac_mute
     - output.turn_on: gain
     - lambda: id(phase) = 1;
     - script.execute: update_led
     
  - id: waiting
    then:   
     - light.turn_on:
          id: top_led
          effect: pulse
          red: 0%
          green: 0%
          blue: 100% 
          brightness: 100% 
     - voice_assistant.stop:              
     - micro_wake_word.start:                       
       

  - id: listening
    then:
     - light.turn_on:
          id: top_led
          effect: pulse
          red: 0%
          green: 100%
          blue: 0%                      
          brightness: 100%       
          
  - id: answering
    then:
     - light.turn_on:
          id: top_led
          effect: none
          red: 100%
          green: 100%
          blue: 0%                     
          brightness: 100%       
          
  - id: external_player
    then:
     - light.turn_on:
          id: top_led
          effect: none
          red: 80%
          green: 40%
          blue: 0%                      
             
  - id: mute_on
    then:
       - media_player.volume_set:
            volume: '0'
       - lambda: id(mute) = true;
       
  - id: mute_off
    then:
       - media_player.volume_set:
            volume: !lambda return(id(Vol));
       - lambda: id(mute) = false;             
            
            
            
      
      
                    
